import { Material, Product, Purchase, Sale, Supplier, AtelierSettings } from '../types';
import {
  DEFAULT_MATERIALS,
  DEFAULT_PRODUCTS,
  DEFAULT_PURCHASES,
  DEFAULT_SALES,
  DEFAULT_SUPPLIERS,
  DEFAULT_SETTINGS
} from './storage';

export interface AtelierPreset {
  id: string;
  title: string;
  subtitle: string;
  badge: string;
  description: string;
  materials: Material[];
  products: Product[];
  purchases: Purchase[];
  sales: Sale[];
  suppliers: Supplier[];
  settings: AtelierSettings;
}

// -------------------------------------------------------------
// 1. COSTURA CRIATIVA, BOLSAS & ACESSÓRIOS
// -------------------------------------------------------------
const PRESET_COSTURA: AtelierPreset = {
  id: 'costura',
  title: 'Costura Criativa & Acessórios',
  subtitle: 'Bolsas, necessaires, estojos, zíperes, tecidos e etiquetas',
  badge: 'Mais Popular',
  description: 'Exemplo completo de confecção artesanal com tecidos, zíperes de metal, alças montadas e etiquetas gravadas como sub-produtos.',
  settings: {
    atelierName: 'Ateliê Joana Slompo',
    artisanName: 'Joana Slompo',
    defaultHourlyRate: 35.0,
    defaultFixedCostPercent: 10,
    defaultProfitMargin: 45,
  },
  suppliers: [
    {
      id: 'sup_c1',
      name: 'Tecidos & Cia Brás',
      phone: '(11) 98765-4321',
      email: 'contato@tecidoscia.com.br',
      website: 'https://tecidoscia.com.br',
      notes: 'Tricolines 100% algodão, sarjas peletizadas e linho misto.',
      createdAt: '2026-08-01',
    },
    {
      id: 'sup_c2',
      name: 'Armarinho & Aviamentos Central',
      phone: '(11) 97654-3210',
      email: 'vendas@armarinhocentral.com.br',
      website: 'https://armarinhocentral.com.br',
      notes: 'Zíperes metálicos, cursores com trava, vivo e sintéticos.',
      createdAt: '2026-08-02',
    },
    {
      id: 'sup_c3',
      name: 'Metais & Ferragens Criativas',
      phone: '(19) 95432-1098',
      email: 'vendas@metaiscriativos.com.br',
      notes: 'Mosquetões ouro velho, rebites nº 2 e reguladores de alça.',
      createdAt: '2026-08-05',
    },
    {
      id: 'sup_c4',
      name: 'Papelaria & Embalagens Kraft',
      phone: '(11) 96543-2109',
      email: 'atendimento@papelembalar.com.br',
      notes: 'Caixas de envio maleta, papel de seda e fita de juta.',
      createdAt: '2026-08-08',
    }
  ],
  materials: [
    {
      id: 'mat_c1',
      name: 'Tricoline 100% Algodão Estampa Botânica',
      category: 'Tecidos & Forros',
      unit: 'cm',
      packageQuantity: 2,
      packageUnit: 'm',
      packagePrice: 76.00,
      unitCost: 0.38,
      currentStock: 350,
      minStock: 80,
      supplierId: 'sup_c1',
      supplierName: 'Tecidos & Cia Brás',
      imageUrl: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=400&auto=format&fit=crop&q=80',
      notes: 'Largura padrão 1,50m. Lavar e passar antes de cortar.',
      createdAt: '2026-08-01',
      updatedAt: '2026-09-01',
    },
    {
      id: 'mat_c2',
      name: 'Sarja Crua 100% Algodão 260g Estruturada',
      category: 'Tecidos & Forros',
      unit: 'cm',
      packageQuantity: 3,
      packageUnit: 'm',
      packagePrice: 84.00,
      unitCost: 0.28,
      currentStock: 420,
      minStock: 100,
      supplierId: 'sup_c1',
      supplierName: 'Tecidos & Cia Brás',
      imageUrl: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?w=400&auto=format&fit=crop&q=80',
      notes: 'Ótima sustentação para corpos de bolsas e forros resistentes.',
      createdAt: '2026-08-01',
      updatedAt: '2026-09-01',
    },
    {
      id: 'mat_c3',
      name: 'Zíper de Metal Dourado Médio nº 5 (Metro)',
      category: 'Aviamentos & Ferragens',
      unit: 'cm',
      packageQuantity: 10,
      packageUnit: 'm',
      packagePrice: 45.00,
      unitCost: 0.045,
      currentStock: 650,
      minStock: 150,
      supplierId: 'sup_c2',
      supplierName: 'Armarinho & Aviamentos Central',
      imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&auto=format&fit=crop&q=80',
      notes: 'Trilho dourado dente de metal.',
      createdAt: '2026-08-02',
      updatedAt: '2026-08-20',
    },
    {
      id: 'mat_c4',
      name: 'Cursor Dourado Gota para Zíper nº 5',
      category: 'Aviamentos & Ferragens',
      unit: 'un',
      packageQuantity: 20,
      packageUnit: 'un',
      packagePrice: 32.00,
      unitCost: 1.60,
      currentStock: 14,
      minStock: 5,
      supplierId: 'sup_c2',
      supplierName: 'Armarinho & Aviamentos Central',
      notes: 'Cursor esmaltado dourado.',
      createdAt: '2026-08-02',
      updatedAt: '2026-08-20',
    },
    {
      id: 'mat_c5',
      name: 'Retalho Sintético Montana 1.4mm Caramelo',
      category: 'Tecidos & Forros',
      unit: 'cm',
      packageQuantity: 50,
      packageUnit: 'cm',
      packagePrice: 30.00,
      unitCost: 0.60,
      currentStock: 45,
      minStock: 10,
      supplierId: 'sup_c2',
      supplierName: 'Armarinho & Aviamentos Central',
      notes: 'Base perfeita para corte de tiras e etiquetas com gravação a laser.',
      createdAt: '2026-08-05',
      updatedAt: '2026-08-28',
    },
    {
      id: 'mat_c6',
      name: 'Alça de Algodão Listrada 30mm',
      category: 'Fitas & Cordões',
      unit: 'm',
      packageQuantity: 25,
      packageUnit: 'm',
      packagePrice: 62.50,
      unitCost: 2.50,
      currentStock: 18,
      minStock: 6,
      supplierId: 'sup_c2',
      supplierName: 'Armarinho & Aviamentos Central',
      notes: 'Alça encorpada padrão bolsa transversal.',
      createdAt: '2026-08-05',
      updatedAt: '2026-08-25',
    },
    {
      id: 'mat_c7',
      name: 'Mosquetão Giratório Ouro Velho 30mm',
      category: 'Aviamentos & Ferragens',
      unit: 'un',
      packageQuantity: 10,
      packageUnit: 'un',
      packagePrice: 28.00,
      unitCost: 2.80,
      currentStock: 12,
      minStock: 4,
      supplierId: 'sup_c3',
      supplierName: 'Metais & Ferragens Criativas',
      notes: 'Giratória resistente com mola reforçada.',
      createdAt: '2026-08-06',
      updatedAt: '2026-08-20',
    },
    {
      id: 'mat_c8',
      name: 'Caixa de Envio Papelão Kraft 24x18x8cm',
      category: 'Embalagens & Envio',
      unit: 'un',
      packageQuantity: 20,
      packageUnit: 'un',
      packagePrice: 44.00,
      unitCost: 2.20,
      currentStock: 15,
      minStock: 5,
      supplierId: 'sup_c4',
      supplierName: 'Papelaria & Embalagens Kraft',
      notes: 'Com fita adesiva personalizada e papel de seda.',
      createdAt: '2026-08-10',
      updatedAt: '2026-09-02',
    }
  ],
  products: [
    // Sub-produto 1: Etiqueta
    {
      id: 'prod_c1',
      name: 'Etiqueta Sintético Montana Gravada',
      category: 'Componentes & Insumos',
      description: 'Etiqueta cortada e gravada a laser com logotipo do ateliê para costurar em peças prontas.',
      isIntermediate: true,
      imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&auto=format&fit=crop&q=80',
      items: [
        {
          id: 'ri_c1_1',
          type: 'material',
          targetId: 'mat_c5',
          name: 'Retalho Sintético Montana 1.4mm Caramelo',
          quantity: 1.5,
          unit: 'cm',
          unitCost: 0.60,
          totalCost: 0.90,
        }
      ],
      materialsCost: 0.90,
      productionTimeMinutes: 3,
      hourlyRate: 35.0,
      laborCost: 1.75,
      fixedCostPercent: 10,
      fixedCost: 0.27,
      otherCosts: 0.08,
      totalCost: 3.00,
      profitMarginPercent: 30,
      suggestedPrice: 4.29,
      actualPrice: 4.00,
      calculatedMarginPercent: 25.0,
      netProfit: 1.00,
      batchYield: 1,
      unitCostFromBatch: 3.00,
      createdAt: '2026-08-10',
      updatedAt: '2026-09-01',
    },
    // Sub-produto 2: Alça pronta
    {
      id: 'prod_c2',
      name: 'Alça Transversal Regulável com Mosquetões',
      category: 'Componentes & Insumos',
      description: 'Alça pronta de 1,40m com regulador de metal e 2 mosquetões nas pontas.',
      isIntermediate: true,
      items: [
        {
          id: 'ri_c2_1',
          type: 'material',
          targetId: 'mat_c6',
          name: 'Alça de Algodão Listrada 30mm',
          quantity: 1.4,
          unit: 'm',
          unitCost: 2.50,
          totalCost: 3.50,
        },
        {
          id: 'ri_c2_2',
          type: 'material',
          targetId: 'mat_c7',
          name: 'Mosquetão Giratório Ouro Velho 30mm',
          quantity: 2,
          unit: 'un',
          unitCost: 2.80,
          totalCost: 5.60,
        }
      ],
      materialsCost: 9.10,
      productionTimeMinutes: 10,
      hourlyRate: 35.0,
      laborCost: 5.83,
      fixedCostPercent: 10,
      fixedCost: 1.49,
      otherCosts: 0.50,
      totalCost: 16.92,
      profitMarginPercent: 35,
      suggestedPrice: 26.03,
      actualPrice: 25.00,
      calculatedMarginPercent: 32.3,
      netProfit: 8.08,
      batchYield: 1,
      unitCostFromBatch: 16.92,
      createdAt: '2026-08-12',
      updatedAt: '2026-09-01',
    },
    // Produto Final 1: Necessaire
    {
      id: 'prod_c3',
      name: 'Necessaire Box Floral com Zíper Dourado',
      category: 'Acessórios & Bolsas',
      description: 'Necessaire espaçosa forrada com sarja, zíper metálico reforçado e etiqueta de sintético aplicada.',
      isIntermediate: false,
      imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&auto=format&fit=crop&q=80',
      items: [
        {
          id: 'ri_c3_1',
          type: 'material',
          targetId: 'mat_c1',
          name: 'Tricoline 100% Algodão Estampa Botânica',
          quantity: 30,
          unit: 'cm',
          unitCost: 0.38,
          totalCost: 11.40,
        },
        {
          id: 'ri_c3_2',
          type: 'material',
          targetId: 'mat_c2',
          name: 'Sarja Crua 100% Algodão 260g Estruturada',
          quantity: 30,
          unit: 'cm',
          unitCost: 0.28,
          totalCost: 8.40,
        },
        {
          id: 'ri_c3_3',
          type: 'material',
          targetId: 'mat_c3',
          name: 'Zíper de Metal Dourado Médio nº 5',
          quantity: 35,
          unit: 'cm',
          unitCost: 0.045,
          totalCost: 1.58,
        },
        {
          id: 'ri_c3_4',
          type: 'material',
          targetId: 'mat_c4',
          name: 'Cursor Dourado Gota para Zíper nº 5',
          quantity: 1,
          unit: 'un',
          unitCost: 1.60,
          totalCost: 1.60,
        },
        // Insumo é o SUB-PRODUTO ETIQUETA!
        {
          id: 'ri_c3_5',
          type: 'product',
          targetId: 'prod_c1',
          name: 'Etiqueta Sintético Montana Gravada',
          quantity: 1,
          unit: 'un',
          unitCost: 3.00,
          totalCost: 3.00,
        }
      ],
      materialsCost: 25.98,
      productionTimeMinutes: 45,
      hourlyRate: 35.0,
      laborCost: 26.25,
      fixedCostPercent: 10,
      fixedCost: 5.22,
      otherCosts: 2.50, // Embalagem e papel de seda
      totalCost: 59.95,
      profitMarginPercent: 45,
      suggestedPrice: 109.00,
      actualPrice: 110.00,
      calculatedMarginPercent: 45.5,
      netProfit: 50.05,
      batchYield: 1,
      unitCostFromBatch: 59.95,
      createdAt: '2026-08-15',
      updatedAt: '2026-09-02',
    },
    // Produto Final 2: Bolsa Tote com alça pronta
    {
      id: 'prod_c4',
      name: 'Bolsa Tote Sarja com Alça Transversal',
      category: 'Acessórios & Bolsas',
      description: 'Bolsa de ombro versátil em sarja crua, com bolso interno, etiqueta e alça transversal removível inclusa.',
      isIntermediate: false,
      imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&auto=format&fit=crop&q=80',
      items: [
        {
          id: 'ri_c4_1',
          type: 'material',
          targetId: 'mat_c2',
          name: 'Sarja Crua 100% Algodão 260g Estruturada',
          quantity: 80,
          unit: 'cm',
          unitCost: 0.28,
          totalCost: 22.40,
        },
        {
          id: 'ri_c4_2',
          type: 'material',
          targetId: 'mat_c1',
          name: 'Tricoline 100% Algodão Estampa Botânica',
          quantity: 30,
          unit: 'cm',
          unitCost: 0.38,
          totalCost: 11.40,
        },
        {
          id: 'ri_c4_3',
          type: 'material',
          targetId: 'mat_c8',
          name: 'Caixa de Envio Papelão Kraft 24x18x8cm',
          quantity: 1,
          unit: 'un',
          unitCost: 2.20,
          totalCost: 2.20,
        },
        // Sub-produto: Alça Pronta
        {
          id: 'ri_c4_4',
          type: 'product',
          targetId: 'prod_c2',
          name: 'Alça Transversal Regulável com Mosquetões',
          quantity: 1,
          unit: 'un',
          unitCost: 16.92,
          totalCost: 16.92,
        },
        // Sub-produto: Etiqueta
        {
          id: 'ri_c4_5',
          type: 'product',
          targetId: 'prod_c1',
          name: 'Etiqueta Sintético Montana Gravada',
          quantity: 1,
          unit: 'un',
          unitCost: 3.00,
          totalCost: 3.00,
        }
      ],
      materialsCost: 55.92,
      productionTimeMinutes: 75,
      hourlyRate: 35.0,
      laborCost: 43.75,
      fixedCostPercent: 10,
      fixedCost: 9.97,
      otherCosts: 3.50,
      totalCost: 113.14,
      profitMarginPercent: 45,
      suggestedPrice: 205.71,
      actualPrice: 210.00,
      calculatedMarginPercent: 46.1,
      netProfit: 96.86,
      batchYield: 1,
      unitCostFromBatch: 113.14,
      createdAt: '2026-08-18',
      updatedAt: '2026-09-03',
    }
  ],
  purchases: [
    {
      id: 'pur_c1',
      date: '2026-08-01',
      supplierId: 'sup_c1',
      supplierName: 'Tecidos & Cia Brás',
      invoiceNumber: 'NF-10482',
      shippingCost: 22.00,
      totalAmount: 182.00,
      items: [
        {
          materialId: 'mat_c1',
          materialName: 'Tricoline 100% Algodão Estampa Botânica',
          quantity: 2,
          unit: 'm',
          packagePrice: 76.00,
          totalPrice: 76.00,
        },
        {
          materialId: 'mat_c2',
          materialName: 'Sarja Crua 100% Algodão 260g',
          quantity: 3,
          unit: 'm',
          packagePrice: 84.00,
          totalPrice: 84.00,
        }
      ],
      notes: 'Reposição para início de coleção outono.',
      createdAt: '2026-08-01',
    },
    {
      id: 'pur_c2',
      date: '2026-08-15',
      supplierId: 'sup_c2',
      supplierName: 'Armarinho & Aviamentos Central',
      invoiceNumber: 'PED-8831',
      shippingCost: 0,
      totalAmount: 169.50,
      items: [
        {
          materialId: 'mat_c3',
          materialName: 'Zíper de Metal Dourado Médio nº 5',
          quantity: 10,
          unit: 'm',
          packagePrice: 45.00,
          totalPrice: 45.00,
        },
        {
          materialId: 'mat_c4',
          materialName: 'Cursor Dourado Gota',
          quantity: 20,
          unit: 'un',
          packagePrice: 32.00,
          totalPrice: 32.00,
        },
        {
          materialId: 'mat_c6',
          materialName: 'Alça de Algodão Listrada 30mm',
          quantity: 25,
          unit: 'm',
          packagePrice: 62.50,
          totalPrice: 62.50,
        },
        {
          materialId: 'mat_c5',
          materialName: 'Retalho Sintético Montana',
          quantity: 50,
          unit: 'cm',
          packagePrice: 30.00,
          totalPrice: 30.00,
        }
      ],
      notes: 'Retirada no balcão sem frete.',
      createdAt: '2026-08-15',
    }
  ],
  sales: [
    {
      id: 'sale_c1',
      date: '2026-09-02',
      productId: 'prod_c3',
      productName: 'Necessaire Box Floral com Zíper Dourado',
      productImageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&auto=format&fit=crop&q=80',
      quantity: 2,
      unitPrice: 110.00,
      unitCost: 59.95,
      totalRevenue: 220.00,
      totalCost: 119.90,
      totalProfit: 100.10,
      marginPercent: 45.5,
      customerName: 'Mariana Castro',
      channel: 'Instagram Direct',
      notes: 'Para presente de aniversário com fita.',
      createdAt: '2026-09-02',
    },
    {
      id: 'sale_c2',
      date: '2026-09-05',
      productId: 'prod_c4',
      productName: 'Bolsa Tote Sarja com Alça Transversal',
      productImageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&auto=format&fit=crop&q=80',
      quantity: 1,
      unitPrice: 210.00,
      unitCost: 113.14,
      totalRevenue: 210.00,
      totalCost: 113.14,
      totalProfit: 96.86,
      marginPercent: 46.1,
      customerName: 'Clara Nogueira',
      channel: 'WhatsApp',
      notes: 'Entrega via motoboy local.',
      createdAt: '2026-09-05',
    },
    {
      id: 'sale_c3',
      date: '2026-09-08',
      productId: 'prod_c3',
      productName: 'Necessaire Box Floral com Zíper Dourado',
      productImageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&auto=format&fit=crop&q=80',
      quantity: 1,
      unitPrice: 110.00,
      unitCost: 59.95,
      totalRevenue: 110.00,
      totalCost: 59.95,
      totalProfit: 50.05,
      marginPercent: 45.5,
      customerName: 'Beatriz Lima',
      channel: 'Elo7',
      createdAt: '2026-09-08',
    }
  ]
};

// -------------------------------------------------------------
// 2. VELAS AROMÁTICAS, SABOARIA & BEM-ESTAR
// -------------------------------------------------------------
const PRESET_VELAS: AtelierPreset = {
  id: 'velas',
  title: 'Velas Artesanais & Rótulos Caseiros',
  subtitle: 'Cera vegetal de coco, essências puras, potes âmbar e rótulos impressos em casa',
  badge: 'Foco do Ateliê',
  description: 'Estrutura completa e refinada para ateliês de velas artesanais. Demonstra a confecção caseira dos próprios rótulos e etiquetas em vinil e papel kraft adesivo com laminação a frio, integrados na precificação de velas aromáticas em potes âmbar, latinhas e wax melts.',
  settings: DEFAULT_SETTINGS,
  suppliers: DEFAULT_SUPPLIERS,
  materials: DEFAULT_MATERIALS,
  products: DEFAULT_PRODUCTS,
  purchases: DEFAULT_PURCHASES,
  sales: DEFAULT_SALES,
};

// -------------------------------------------------------------
// 3. PAPELARIA FINA, ENCADERNAÇÃO & CARTONAGEM
// -------------------------------------------------------------
const PRESET_ENCADERNACAO: AtelierPreset = {
  id: 'papelaria',
  title: 'Encadernação Artesanal & Cartonagem',
  subtitle: 'Planners, cadernos costurados, papelão cinza, papéis finos e caixas',
  badge: 'Papelaria Fina',
  description: 'Projetos de encadernação onde a capa dura montada e miolo costurado atuam como sub-produtos de livros e caixas cartonadas.',
  settings: {
    atelierName: 'Ateliê Traço & Papel',
    artisanName: 'Joana Slompo',
    defaultHourlyRate: 38.0,
    defaultFixedCostPercent: 10,
    defaultProfitMargin: 48,
  },
  suppliers: [
    {
      id: 'sup_p1',
      name: 'Distribuidora de Papéis Especiais',
      phone: '(11) 97788-9900',
      email: 'papeis@especiais.com.br',
      notes: 'Papéis pólen bold 90g, kraft 240g e papelão cinza roller.',
      createdAt: '2026-08-01',
    },
    {
      id: 'sup_p2',
      name: 'Ferragens & Acessórios para Livros',
      phone: '(11) 98899-0011',
      notes: 'Cantoneiras metálicas, elásticos lurex e cabeceados.',
      createdAt: '2026-08-02',
    }
  ],
  materials: [
    {
      id: 'mat_p1',
      name: 'Papelão Cinza Roller 2.0mm (Chapa 80x100cm)',
      category: 'Papelaria & Tags',
      unit: 'folha',
      packageQuantity: 10,
      packageUnit: 'folha',
      packagePrice: 55.00,
      unitCost: 5.50,
      currentStock: 18,
      minStock: 4,
      supplierId: 'sup_p1',
      supplierName: 'Distribuidora de Papéis Especiais',
      notes: 'Rende 12 capas A5 por chapa.',
      createdAt: '2026-08-01',
      updatedAt: '2026-09-01',
    },
    {
      id: 'mat_p2',
      name: 'Papel Pólen Bold 90g Marfim A4 (Resma 500fls)',
      category: 'Papelaria & Tags',
      unit: 'folha',
      packageQuantity: 500,
      packageUnit: 'folha',
      packagePrice: 65.00,
      unitCost: 0.13,
      currentStock: 650,
      minStock: 100,
      supplierId: 'sup_p1',
      supplierName: 'Distribuidora de Papéis Especiais',
      imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80',
      notes: 'Folhas sem brilho de alta gramatura, perfeitas para escrita com caneta tinteiro.',
      createdAt: '2026-08-01',
      updatedAt: '2026-09-01',
    },
    {
      id: 'mat_p3',
      name: 'Tecido Linho Misto Especial para Revestimento',
      category: 'Tecidos & Forros',
      unit: 'cm',
      packageQuantity: 1,
      packageUnit: 'm',
      packagePrice: 48.00,
      unitCost: 0.48,
      currentStock: 140,
      minStock: 30,
      supplierId: 'sup_p1',
      supplierName: 'Distribuidora de Papéis Especiais',
      notes: 'Engomado próprio para colagem sem manchar.',
      createdAt: '2026-08-02',
      updatedAt: '2026-08-25',
    },
    {
      id: 'mat_p4',
      name: 'Elástico Chato Lurex Ouro 10mm (Rolo 25m)',
      category: 'Fitas & Cordões',
      unit: 'm',
      packageQuantity: 25,
      packageUnit: 'm',
      packagePrice: 32.50,
      unitCost: 1.30,
      currentStock: 20,
      minStock: 5,
      supplierId: 'sup_p2',
      supplierName: 'Ferragens & Acessórios para Livros',
      notes: 'Fechamento de cadernos e planners.',
      createdAt: '2026-08-03',
      updatedAt: '2026-08-20',
    },
    {
      id: 'mat_p5',
      name: 'Cantoneira Metálica Dourada para Capa (Cento)',
      category: 'Aviamentos & Ferragens',
      unit: 'un',
      packageQuantity: 100,
      packageUnit: 'un',
      packagePrice: 24.00,
      unitCost: 0.24,
      currentStock: 78,
      minStock: 16,
      supplierId: 'sup_p2',
      supplierName: 'Ferragens & Acessórios para Livros',
      notes: 'Proteção para os 4 cantos da capa.',
      createdAt: '2026-08-04',
      updatedAt: '2026-08-20',
    }
  ],
  products: [
    // Sub-produto: Capa Dura
    {
      id: 'prod_p1',
      name: 'Capa Dura Revestida em Linho A5 com Elástico',
      category: 'Componentes & Insumos',
      description: 'Conjunto de capa frente e verso cortada no papelão 2mm, forrada em linho e furada.',
      isIntermediate: true,
      items: [
        {
          id: 'ri_p1_1',
          type: 'material',
          targetId: 'mat_p1',
          name: 'Papelão Cinza Roller 2.0mm',
          quantity: 0.16,
          unit: 'folha',
          unitCost: 5.50,
          totalCost: 0.88,
        },
        {
          id: 'ri_p1_2',
          type: 'material',
          targetId: 'mat_p3',
          name: 'Tecido Linho Misto Especial',
          quantity: 25,
          unit: 'cm',
          unitCost: 0.48,
          totalCost: 12.00,
        },
        {
          id: 'ri_p1_3',
          type: 'material',
          targetId: 'mat_p4',
          name: 'Elástico Chato Lurex Ouro 10mm',
          quantity: 0.35,
          unit: 'm',
          unitCost: 1.30,
          totalCost: 0.455,
        }
      ],
      materialsCost: 13.34,
      productionTimeMinutes: 20,
      hourlyRate: 38.0,
      laborCost: 12.67,
      fixedCostPercent: 10,
      fixedCost: 2.60,
      otherCosts: 0.50,
      totalCost: 29.11,
      profitMarginPercent: 30,
      suggestedPrice: 41.58,
      actualPrice: 42.00,
      calculatedMarginPercent: 30.7,
      netProfit: 12.89,
      batchYield: 1,
      unitCostFromBatch: 29.11,
      createdAt: '2026-08-10',
      updatedAt: '2026-09-01',
    },
    // Produto Final: Caderno A5
    {
      id: 'prod_p2',
      name: 'Caderno Artesanal A5 Costura Copta 160 Páginas',
      category: 'Papelaria & Cadernos',
      description: 'Caderno costurado à mão com linha encerada, miolo em papel pólen 90g e cantoneiras douradas.',
      isIntermediate: false,
      imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80',
      items: [
        {
          id: 'ri_p2_1',
          type: 'product',
          targetId: 'prod_p1',
          name: 'Capa Dura Revestida em Linho A5',
          quantity: 1,
          unit: 'un',
          unitCost: 29.11,
          totalCost: 29.11,
        },
        {
          id: 'ri_p2_2',
          type: 'material',
          targetId: 'mat_p2',
          name: 'Papel Pólen Bold 90g Marfim A4',
          quantity: 40, // 40 folhas dobradas = 160 págs A5
          unit: 'folha',
          unitCost: 0.13,
          totalCost: 5.20,
        },
        {
          id: 'ri_p2_3',
          type: 'material',
          targetId: 'mat_p5',
          name: 'Cantoneira Metálica Dourada para Capa',
          quantity: 4,
          unit: 'un',
          unitCost: 0.24,
          totalCost: 0.96,
        }
      ],
      materialsCost: 35.27,
      productionTimeMinutes: 45,
      hourlyRate: 38.0,
      laborCost: 28.50,
      fixedCostPercent: 10,
      fixedCost: 6.38,
      otherCosts: 2.00,
      totalCost: 72.15,
      profitMarginPercent: 48,
      suggestedPrice: 138.75,
      actualPrice: 140.00,
      calculatedMarginPercent: 48.5,
      netProfit: 67.85,
      batchYield: 1,
      unitCostFromBatch: 72.15,
      createdAt: '2026-08-15',
      updatedAt: '2026-09-02',
    }
  ],
  purchases: [
    {
      id: 'pur_p1',
      date: '2026-08-01',
      supplierId: 'sup_p1',
      supplierName: 'Distribuidora de Papéis Especiais',
      shippingCost: 25.00,
      totalAmount: 193.00,
      items: [
        {
          materialId: 'mat_p1',
          materialName: 'Papelão Cinza Roller 2.0mm',
          quantity: 10,
          unit: 'folha',
          packagePrice: 55.00,
          totalPrice: 55.00,
        },
        {
          materialId: 'mat_p2',
          materialName: 'Papel Pólen Bold 90g Marfim',
          quantity: 500,
          unit: 'folha',
          packagePrice: 65.00,
          totalPrice: 65.00,
        },
        {
          materialId: 'mat_p3',
          materialName: 'Tecido Linho Misto Especial',
          quantity: 1,
          unit: 'm',
          packagePrice: 48.00,
          totalPrice: 48.00,
        }
      ],
      createdAt: '2026-08-01',
    }
  ],
  sales: [
    {
      id: 'sale_p1',
      date: '2026-09-04',
      productId: 'prod_p2',
      productName: 'Caderno Artesanal A5 Costura Copta 160 Páginas',
      productImageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80',
      quantity: 2,
      unitPrice: 140.00,
      unitCost: 72.15,
      totalRevenue: 280.00,
      totalCost: 144.30,
      totalProfit: 135.70,
      marginPercent: 48.5,
      customerName: 'Larissa Fontes',
      channel: 'Feira Criativa',
      createdAt: '2026-09-04',
    }
  ]
};

// -------------------------------------------------------------
// 4. CROCHÊ, TRICÔ & AMIGURUMI
// -------------------------------------------------------------
const PRESET_CROCHE: AtelierPreset = {
  id: 'croche',
  title: 'Crochê, Tricô & Amigurumi',
  subtitle: 'Fios 100% algodão, enchimento, olhos com trava, tags e bichinhos',
  badge: 'Fios & Afetos',
  description: 'Precificação precisa para artesãos de crochê que precisam controlar metros de fio, fibra siliconada e tags de couro aplicadas.',
  settings: {
    atelierName: 'Ateliê Ponto & Laçada',
    artisanName: 'Joana Slompo',
    defaultHourlyRate: 30.0,
    defaultFixedCostPercent: 8,
    defaultProfitMargin: 45,
  },
  suppliers: [
    {
      id: 'sup_cr1',
      name: 'Círculo dos Fios & Lãs',
      phone: '(11) 98222-3344',
      email: 'fios@circulodosfios.com.br',
      notes: 'Fios amigurumi tradicionais, maxi e fio de malha premium.',
      createdAt: '2026-08-01',
    },
    {
      id: 'sup_cr2',
      name: 'Armarinho Santa Clara',
      phone: '(11) 97333-4455',
      notes: 'Olhos com trava de segurança, focinhos e fibra siliconada pura.',
      createdAt: '2026-08-02',
    }
  ],
  materials: [
    {
      id: 'mat_cr1',
      name: 'Fio Amigurumi 100% Algodão Mercerizado (Novelo 254m)',
      category: 'Linhas & Fios',
      unit: 'm',
      packageQuantity: 254,
      packageUnit: 'm',
      packagePrice: 16.50,
      unitCost: 0.065,
      currentStock: 480,
      minStock: 100,
      supplierId: 'sup_cr1',
      supplierName: 'Círculo dos Fios & Lãs',
      imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=400&auto=format&fit=crop&q=80',
      notes: 'Cores: Mostarda, Caramelo e Off-white.',
      createdAt: '2026-08-01',
      updatedAt: '2026-09-01',
    },
    {
      id: 'mat_cr2',
      name: 'Fibra Siliconada Antialérgica Extra Virgem (1kg)',
      category: 'Tecidos & Forros',
      unit: 'g',
      packageQuantity: 1000,
      packageUnit: 'g',
      packagePrice: 35.00,
      unitCost: 0.035,
      currentStock: 2400,
      minStock: 400,
      supplierId: 'sup_cr2',
      supplierName: 'Armarinho Santa Clara',
      notes: 'Enchimento lavável de alta resiliência.',
      createdAt: '2026-08-02',
      updatedAt: '2026-09-01',
    },
    {
      id: 'mat_cr3',
      name: 'Par de Olhos Pretos com Trava nº 11',
      category: 'Aviamentos & Ferragens',
      unit: 'par',
      packageQuantity: 10,
      packageUnit: 'par',
      packagePrice: 15.00,
      unitCost: 1.50,
      currentStock: 14,
      minStock: 4,
      supplierId: 'sup_cr2',
      supplierName: 'Armarinho Santa Clara',
      notes: 'Seguro para bebês e crianças.',
      createdAt: '2026-08-03',
      updatedAt: '2026-08-20',
    },
    {
      id: 'mat_cr4',
      name: 'Tag Redonda de Couro Sintético com Rebite',
      category: 'Componentes & Insumos',
      unit: 'un',
      packageQuantity: 50,
      packageUnit: 'un',
      packagePrice: 40.00,
      unitCost: 0.80,
      currentStock: 38,
      minStock: 10,
      supplierId: 'sup_cr2',
      supplierName: 'Armarinho Santa Clara',
      notes: 'Gravação "Feito à Mão com Amor".',
      createdAt: '2026-08-04',
      updatedAt: '2026-08-25',
    }
  ],
  products: [
    {
      id: 'prod_cr1',
      name: 'Amigurumi Leãozinho Juba Caramelo (22cm)',
      category: 'Amigurumis & Brinquedos',
      description: 'Leãozinho confeccionado em crochê com fio 100% algodão, olhos com trava e enchimento hipoalergênico.',
      isIntermediate: false,
      imageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=400&auto=format&fit=crop&q=80',
      items: [
        {
          id: 'ri_cr1_1',
          type: 'material',
          targetId: 'mat_cr1',
          name: 'Fio Amigurumi 100% Algodão Mercerizado',
          quantity: 140, // 140 metros
          unit: 'm',
          unitCost: 0.065,
          totalCost: 9.10,
        },
        {
          id: 'ri_cr1_2',
          type: 'material',
          targetId: 'mat_cr2',
          name: 'Fibra Siliconada Antialérgica',
          quantity: 110, // 110g
          unit: 'g',
          unitCost: 0.035,
          totalCost: 3.85,
        },
        {
          id: 'ri_cr1_3',
          type: 'material',
          targetId: 'mat_cr3',
          name: 'Par de Olhos Pretos com Trava nº 11',
          quantity: 1,
          unit: 'par',
          unitCost: 1.50,
          totalCost: 1.50,
        },
        {
          id: 'ri_cr1_4',
          type: 'material',
          targetId: 'mat_cr4',
          name: 'Tag Redonda de Couro Sintético',
          quantity: 1,
          unit: 'un',
          unitCost: 0.80,
          totalCost: 0.80,
        }
      ],
      materialsCost: 15.25,
      productionTimeMinutes: 180, // 3 horas de crochê detalhado
      hourlyRate: 30.0,
      laborCost: 90.00,
      fixedCostPercent: 8,
      fixedCost: 8.42,
      otherCosts: 3.00, // Saquinho de algodão cru para embalagem
      totalCost: 116.67,
      profitMarginPercent: 45,
      suggestedPrice: 212.13,
      actualPrice: 220.00,
      calculatedMarginPercent: 47.0,
      netProfit: 103.33,
      batchYield: 1,
      unitCostFromBatch: 116.67,
      createdAt: '2026-08-12',
      updatedAt: '2026-09-02',
    }
  ],
  purchases: [
    {
      id: 'pur_cr1',
      date: '2026-08-01',
      supplierId: 'sup_cr1',
      supplierName: 'Círculo dos Fios & Lãs',
      shippingCost: 18.00,
      totalAmount: 117.00,
      items: [
        {
          materialId: 'mat_cr1',
          materialName: 'Fio Amigurumi 100% Algodão',
          quantity: 6,
          unit: 'un',
          packagePrice: 16.50,
          totalPrice: 99.00,
        }
      ],
      createdAt: '2026-08-01',
    }
  ],
  sales: [
    {
      id: 'sale_cr1',
      date: '2026-09-05',
      productId: 'prod_cr1',
      productName: 'Amigurumi Leãozinho Juba Caramelo (22cm)',
      productImageUrl: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=400&auto=format&fit=crop&q=80',
      quantity: 1,
      unitPrice: 220.00,
      unitCost: 116.67,
      totalRevenue: 220.00,
      totalCost: 116.67,
      totalProfit: 103.33,
      marginPercent: 47.0,
      customerName: 'Juliana Paiva',
      channel: 'Instagram Direct',
      notes: 'Enfeite de porta de maternidade.',
      createdAt: '2026-09-05',
    }
  ]
};

// -------------------------------------------------------------
// 5. ATELIÊ EM BRANCO (ZERADO)
// -------------------------------------------------------------
const PRESET_LIMPO: AtelierPreset = {
  id: 'limpo',
  title: 'Ateliê em Branco (Começar do Zero)',
  subtitle: 'Sem itens de teste, pronto para cadastrar suas peças reais',
  badge: 'Personalizado',
  description: 'Limpa todos os materiais, produtos e vendas de demonstração para você começar a cadastrar diretamente os seus materiais e receitas reais.',
  settings: {
    atelierName: 'Meu Ateliê',
    artisanName: 'Joana Slompo',
    defaultHourlyRate: 35.0,
    defaultFixedCostPercent: 10,
    defaultProfitMargin: 45,
  },
  suppliers: [],
  materials: [],
  products: [],
  purchases: [],
  sales: [],
};

export const ATELIER_PRESETS: AtelierPreset[] = [
  PRESET_COSTURA,
  PRESET_VELAS,
  PRESET_ENCADERNACAO,
  PRESET_CROCHE,
  PRESET_LIMPO,
];
